WebApp/Models/DropdownValues.cs
using System.Collections.Generic;
using System.Linq;

namespace WebApp.Models
{
    public class DropdownValues
    {
        public string Url { get; set; }
        public string ActiveValueName { get; set; }

        public IEnumerable<(string name, string value)> AllDropdownEntries { get; set; } =
            new List<(string name, string value)>();

        public IEnumerable<(string key, string value)> OtherQueryParams { get; set; } =
            new List<(string key, string value)>();

        public string FilterParameterName { get; set; }

        public string GetUrl(string dropDownValue)
        {
            var queryString = OtherQueryParams
                .Select(tuple => $"{tuple.key}={tuple.value}").Prepend($"{FilterParameterName}={dropDownValue}");
            return $"{Url}?{string.Join("&", queryString)}";
        }
    }
}

WebApp/Models/OrderListViewModel.cs
using System.Collections.Generic;
using Application.Orders;
using Domain.Orders;

namespace WebApp.Models
{
    public class OrderListViewModel
    {
        public OrderStatus CurrentFilter { get; set; }
        public IEnumerable<OrderListItemDto> ListItems { get; set; }
    }
}

WebApp/Models/PageMessage.cs
namespace WebApp.Models
{
    public class PageMessage
    {
        public string Value { get; set; }
        public MessageType MessageType { get; set; }
    }

    public enum MessageType
    {
        Success,
        Error,
        Info
    }
}

WebApp/Models/TopSoldProductsViewModel.cs
using System.Collections.Generic;
using Application.Products;
using Domain.Orders;

namespace WebApp.Models
{
    public class TopSoldProductsViewModel
    {
        public IEnumerable<int> QuantityFilterValues { get; set; }
        public OrderStatus CurrentStatusFilter { get; set; }
        public int CurrentQuantityFilter { get; set; }
        public IEnumerable<TopSoldProductDto> ProductList { get; set; }
    }
}

WebApp/Controllers/BaseController.cs
using System;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace WebApp.Controllers
{
    public abstract class BaseController : Controller
    {
        private readonly Lazy<IMediator> _mediator;

        protected BaseController()
        {
            _mediator = new Lazy<IMediator>(() => HttpContext.RequestServices.GetService<IMediator>());
        }

        protected IMediator Mediator => _mediator.Value;
    }
}

WebApp/Controllers/ErrorController.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class ErrorController : Controller
    {
        private const string Msg404 = "Oops... resource could not be found";
        private const string MsgGeneric = "Oops... somthing went wrong. Please contact application administrator";

        [Route("error/{code:int}")]
        public IActionResult Error(int code)
        {
            var vm = (code, code == (int) HttpStatusCode.NotFound ? Msg404 : MsgGeneric);
            return View(vm);
        }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/OrdersController.cs
using System.Threading.Tasks;
using Application.Orders;
using Domain.Orders;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class OrdersController : BaseController
    {
        public async Task<IActionResult> List(int statusFilter = 0)
        {
            OrderStatus.TryFromValue(statusFilter, out var filterValue);
            var orders = await Mediator.Send(
                new ListOrders.Query
                {
                    StatusFilter = filterValue
                });
            return View(new OrderListViewModel
            {
                ListItems = orders,
                CurrentFilter = filterValue
            });
        }
    }
}

WebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Products;
using Domain.Orders;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ProductsController : BaseController
    {
        private static readonly IReadOnlyList<int> AllowedFilterValues = Array.AsReadOnly(new[] {5, 10, 15});

        public async Task<IActionResult> TopSold(int quantityFilter = 5, int statusFilter = 0)
        {
            OrderStatus.TryFromValue(statusFilter, out var statusFilterValue);
            var quantityFilterValue = AllowedFilterValues.Contains(quantityFilter) ? quantityFilter : 5;
            var products = await Mediator.Send(new ListTopProductsSold.Query
            {
                StatusFilter = statusFilterValue,
                QuantityFilter = quantityFilterValue
            });

            var viewModel = new TopSoldProductsViewModel
            {
                QuantityFilterValues = AllowedFilterValues,
                CurrentStatusFilter = statusFilterValue,
                CurrentQuantityFilter = quantityFilterValue,
                ProductList = products
            };
            return View(viewModel);
        }

        [Route("Products/Edit/{merchantProductNo}")]
        public async Task<IActionResult> Edit(string merchantProductNo)
        {
            var product = await Mediator.Send(new GetProductDetails.Query {MerchantNo = merchantProductNo});
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStock(string merchantProductNo, int stock)
        {
            await Mediator.Send(new UpdateProductStock.Command
            {
                MerchantProductNo = merchantProductNo,
                Stock = stock
            });
            return RedirectToAction("Edit", new {merchantProductNo});
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    await Html.RenderPartialAsync("_RenderPageMessages");
}

<div class="jumbotron">
    <h1 class="display-4">Hello, Channel Engine!</h1>
    <p class="lead">This is a simple app utilizing Channel Engine API</p>
    <hr class="my-4">
    <p>It uses .net core and CQRS</p>
</div>

WebApp/Views/Orders/List.cshtml
@using Domain.Orders
@model OrderListViewModel

@{
    ViewData["Title"] = "Order List";
}
<div class="mb-4 d-inline-flex align-items-center flex-wrap">
    <h2 class="mr-2">Orders from </h2>
    @{
        const string allStatusName = "All Statuses";
        var hasFilter = Model.CurrentFilter != null;
        await Html.RenderPartialAsync("_FilterDropdown", new DropdownValues
        {
            ActiveValueName = hasFilter ? $"{Model.CurrentFilter.DisplayName} Status" : allStatusName,
            AllDropdownEntries = OrderStatus.List
                .OrderBy(l => l.Value)
                .Select(s => ($"{s.DisplayName} Status", s.Value.ToString()))
                .Prepend((allStatusName, "0")),
            FilterParameterName = "statusFilter",
            Url = Url.Action("List")
        });
    }
</div>


<table class="table table-hover">
    <thead>
    <tr>
        <th>Id</th>
        <th>Order Date</th>
        <th>Status</th>
        <th>Number of products</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var order in Model.ListItems)
    {
        <tr>
            <td>@order.Id</td>
            <td>@order.OrderDate</td>
            <td>@order.OrderStatus.DisplayName</td>
            <td>@order.NumberOfProducts</td>
            <td>@order.Total</td>
        </tr>
    }
    </tbody>
</table>

WebApp/Views/Products/Edit.cshtml
@model Application.Products.ProductDetailsDto

@{
    ViewData["Title"] = "Edit Product Page";
    await Html.RenderPartialAsync("_RenderPageMessages");
}
<div class="card">
    <div class="card-header">
        <h3>Product @Model.Name</h3>
    </div>

    <div class="card-body">
        <form asp-action="UpdateStock" method="post">
            <input type="hidden" asp-for="MerchantProductNo"/>
            <dl class="row">
                <dt class="col-sm-3">Name</dt>
                <dd class="col-sm-9">@Model.Name</dd>

                <dt class="col-sm-3">Ean</dt>
                <dd class="col-sm-9">@Model.Ean</dd>

                <dt class="col-sm-3">MerchantProductNo</dt>
                <dd class="col-sm-9">@Model.MerchantProductNo</dd>

                <dt class="col-sm-3">Price</dt>
                <dd class="col-sm-9">@Model.Price</dd>

                <dt class="col-sm-3">Brand</dt>
                <dd class="col-sm-9">@Model.Brand</dd>

                <dt class="col-sm-3">Color</dt>
                <dd class="col-sm-9">@Model.Color</dd>

                <dt class="col-sm-3">Size</dt>
                <dd class="col-sm-9">@Model.Size</dd>

                <dt class="col-sm-3">Description</dt>
                <dd class="col-sm-9">@Html.Raw(Model.Description)</dd>

                <dt class="col-sm-3">
                    <label for="stock">Stock</label>
                </dt>
                <dd class="col-sm-9">
                    <input type="number" min="0" asp-for="Stock" class="form-control form-control-sm w-25" id="stock" placeholder="Stock">
                </dd>
            </dl>
            <button class="btn btn-success btn-lg float-right" type="submit">Save</button>

        </form>
    </div>
</div>

WebApp/Views/Products/TopSold.cshtml
@using Domain.Orders
@model TopSoldProductsViewModel

@{
    ViewData["Title"] = "Top Sold Products";
}
<div class="mb-4 d-inline-flex align-items-center flex-wrap">
    <h2 class="mr-2">Top </h2>
    @{
        const string statusFilterParamName = "statusFilter";
        const string quantityFilterParamName = "quantityFilter";
        var hasStatusFilter = Model.CurrentStatusFilter != null;

        await Html.RenderPartialAsync("_FilterDropdown", new DropdownValues
        {
            ActiveValueName = Model.CurrentQuantityFilter.ToString(),
            AllDropdownEntries = Model.QuantityFilterValues
                .Select(v => (v.ToString(), v.ToString())),
            FilterParameterName = quantityFilterParamName,
            Url = Url.Action("TopSold"),
            OtherQueryParams = hasStatusFilter ?
                new[] {(statusFilterParamName, Model.CurrentStatusFilter.Value.ToString())} :
                Enumerable.Empty<(string,string)>()
        });
    }

    <h2 class="ml-2 mr-2">Products sold in orders with</h2>
    @{
        const string allStatusName = "Any Status";
        await Html.RenderPartialAsync("_FilterDropdown", new DropdownValues
        {
            ActiveValueName = hasStatusFilter ? $"{Model.CurrentStatusFilter.DisplayName} Status" : allStatusName,
            AllDropdownEntries = OrderStatus.List
                .OrderBy(l => l.Value)
                .Select(s => ($"{s.DisplayName} Status", s.Value.ToString()))
                .Prepend((allStatusName, "0")),
            FilterParameterName = statusFilterParamName,
            Url = Url.Action("TopSold"),
            OtherQueryParams = new[] {(quantityFilterParamName, Model.CurrentQuantityFilter.ToString())}
        });
    }
</div>


<table class="table table-hover">
    <thead>
    <tr>
        <th>Name</th>
        <th>Ean</th>
        <th>Quantity Sold</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var product in Model.ProductList)
    {
        <tr>
            <td>@product.Name</td>
            <td>@product.Ean</td>
            <td>@product.QuantitySold</td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-merchantProductNo="@product.MerchantProductNo">Edit</a>
            </td>
        </tr>
    }
    </tbody>
</table>

WebApp/Views/Shared/_FilterDropdown.cshtml
@model DropdownValues

<div class="dropdown show">
    <a class="font-weight-bold btn btn-lg btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @Model.ActiveValueName
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        @foreach (var entry in Model.AllDropdownEntries.Where(n => Model.ActiveValueName != n.name))
        {
            <a class="dropdown-item" href="@Model.GetUrl(entry.value)">@entry.name</a>
        }
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="List">Order List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="TopSold">Top Sold Products</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Michal Kobiec
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", false)
</body>
</html>

WebApp/Views/Shared/_RenderPageMessages.cshtml
@using WebApp.Utilities
@functions {

    private static string ResolveAlertType(MessageType type)
    {
        return type switch
        {
            MessageType.Success => "success",
            MessageType.Error => "danger",
            MessageType.Info => "info",
            _ => "light"
            };
    }

}

@foreach (var message in Html.GetPageMessages())
{
    <div class="alert alert-@ResolveAlertType(message.MessageType) alert-dismissible fade show" role="alert">
        @message.Value
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}